sudo: false

language: c

os:
  - osx
  - linux

compiler:
  - gcc
  - clang

env:
  matrix:
    - export v=4
    - export v=5

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libc6-dev
      - pkg-config
      - libtool
      - autoconf
      - automake
      - gcc-4.9
      - g++-4.9
      - clang

branches:
  only:
    - master

before_install:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CC=gcc-4.9 && export CXX=g++-4.9 fi
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then git clone https://github.com/creationix/nvm .nvm && source .nvm/nvm.sh; fi
  - nvm i $v

install:
  - npm i

script:
  - npm t

notifications:
  email: false
