sudo: false

language: c

os:
  - osx
  - linux

compiler:
  - gcc
  - clang

env:
  matrix:
    - export v="4"
    - export v="5"

dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libc6-dev
      - pkg-config
      - libtool
      - autoconf
      - automake
      - gcc-4.9
      - g++-4.9
      - clang
      - libssl-dev

branches:
  only:
    - master

before_install:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CC=gcc-4.9 && export CXX=g++-4.9; fi
  - cc -v
  - CC -v
  - nvm i $v
  - node -v

install:
  - npm i

script:
  - npm t

notifications:
  email: false
