sudo: false

language: c

os:
  - osx
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9

env:
  - NODE_V="node"

before_install:
  - rm -rf ~/.nvm ~/.npm && git clone https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh && nvm install $NODE_V
  - export CXX=g++-4.9
  - export CC=gcc-4.9

install:
  - npm i

script:
  - npm t

notifications:
  email: false
