var lib  = require('./build/Release/mill.node');
module.exports = ctx = {
  test          : lib.test,
  trace         : lib.trace,
  tcplisten     : lib.tcplisten,
  tcpaccept     : lib.tcpaccept,
  tcpconnect    : lib.tcpconnect,
  tcpsend       : lib.tcpsend,
  tcpflush      : lib.tcpflush,
  tcprecv       : lib.tcprecv,
  tcprecvuntil  : lib.tcprecvuntil,
  tcpattach     : lib.tcpattach,
  tcpdetach     : lib.tcpdetach,
  tcpport       : lib.tcpport,
  tcpclose      : lib.tcpclose,
  udplisten     : lib.udplisten,
  udpport       : lib.udpport,
  udpsend       : lib.udpsend,
  udprecv       : lib.udprecv,
  udpclose      : lib.udpclose,
  udpattach     : lib.udpattach,
  udpdetach     : lib.udpdetach,
}
